---
title: "Report for TMDb"
author: "Boiko_Ustym"
date: "2023-09-26"
output:  
  html_document:
    df_print: paged
---

```{r, message=FALSE, warning=FALSE}
# Завантаження покетів та набору даних
library(tidyverse)
TMDB <- read_csv("U:/Master's_work_Boiko/Data_Analysis_movie/tmdb_movies.csv")
TMDB
```

```{r}
# Кількість зміних і спостережень
dim(TMDB)
```

```{r}
# Імена зміних
names(TMDB)
```
```{r}
# Видалення нерелевантних даних
TMDB_cleaned <- TMDB %>% select(-c(id, imdb_id, popularity, budget_adj, revenue_adj, cast, homepage, director, tagline, keywords, overview, production_companies, release_date))
TMDB_cleaned
```
```{r}
# Перевірка кількість NA значень у кожній змінній
na_count <- sapply(TMDB_cleaned, function(y) sum(length(which(is.na(y)))))
print(na_count)
```

```{r}
# Видалення рядків, які містять NA значення
TMDB_cleaned <- na.omit(TMDB_cleaned)
print(sum(is.na(TMDB_cleaned)))
```
```{r}
# Перевірка кількість NA значень у кожній змінній
na_count <- sapply(TMDB_cleaned, function(y) sum(length(which(is.na(y)))))
# Перевірка результату
print(na_count)
```
```{r}
# Кількість зміних і спостережень
dim(TMDB_cleaned)
```
```{r}
# Перевірка на кількість 0 значень у кожній змінній
zero_count <- sapply(TMDB_cleaned, function(y) sum(y == 0, na.rm = TRUE))
print(zero_count)
```
```{r}
# Видалення рядків, де budget, revenue та runtime дорівнює 0
TMDB_cleaned <- TMDB_cleaned %>%
  filter(budget > 0 & revenue > 0 & runtime > 0)
# Встановлення параметра scipen
options(scipen=999)
# Визначення мінімального значення для змінних budget, revenue та runtime
min_data <- sapply(TMDB_cleaned[, c("runtime", "budget", "revenue")], min, na.rm = TRUE)
min_data 
```
```{r}
# Кількість зміних і спостережень
dim(TMDB_cleaned)
```
```{r}
# Перевірка на наявність дублікатів
original_nrow <- nrow(TMDB_cleaned)
duplicated_rows <- TMDB_cleaned[duplicated(TMDB_cleaned),]

# Якщо є дублікати, вивести їх кількість
if(nrow(duplicated_rows) > 0) {
  print(paste("Number of duplicated rows: ", nrow(duplicated_rows)))
}
```
```{r}
# Видалення дублікатів
TMDB_cleaned <- distinct(TMDB_cleaned)

# Перевірка результату
new_nrow <- nrow(TMDB_cleaned)
print(paste("Кількість рядків до видалення дублікатів: ", original_nrow))
print(paste("Кількість рядків після видалення дублікатів: ", new_nrow))
```
```{r}
# Встановлення порогового значення
revenue_threshold <- 11000
budget_threshold <- 1000

# Відфільтровування фільмів з касовими зборами та бюджетом нижче порогового значення
TMDB_cleaned <- TMDB_cleaned %>%
  filter(revenue > revenue_threshold & budget > budget_threshold)

# Перевірка результату
summary(TMDB_cleaned$budget )
summary(TMDB_cleaned$revenue )
```

```{r}
# Фільтрування фільмів з касовими зборами менше за 20000 тисяч
low_revenue_movies <- TMDB_cleaned %>%
  filter(revenue > 20000)

# Виведення перших рядків цього списка для перевірки
low_revenue_movies
```
```{r}
# Виведення структури DataFrame, що включає імена та типи змінних, а також перші кілька значень кожної змінної
str(TMDB_cleaned)
```

```{r}
# Перевірка розміру DataFrame
print(paste("Кількість рядків: ", nrow(TMDB_cleaned)))
print(paste("Кількість стовбців: ", ncol(TMDB_cleaned)))
```
```{r}
# Перевірка загальних статистичних характеристик змінних
summary(TMDB_cleaned)
```
```{r}
# Перевірка перших та останніх рядків DataFrame
head(TMDB_cleaned)
tail(TMDB_cleaned)
```
```{r}
# Розподіл рейтингу фільму (vote_average)
ggplot(TMDB_cleaned, aes(x=vote_average)) + 
  geom_histogram(binwidth=0.5, fill="blue", color="black", alpha=0.7) + 
  labs(title="Розподіл рейтингу фільмів", x="Рейтинг", y="Кількість фільмів")
```
```{r}

library(patchwork)
library(scales) # Для dollar_format

# Графік бюджету з коригуванням осі X
p1 <- ggplot(TMDB_cleaned, aes(x=budget)) + 
  geom_histogram(bins=30, fill="blue") + 
  scale_x_continuous(labels = dollar_format(prefix = "$", suffix = "", big.mark = ",")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + # Нахил тексту
  ggtitle("Бюджет") +
  xlab("Бюджет (в доларах)")

# Графік доходу з коригуванням осі X
p2 <- ggplot(TMDB_cleaned, aes(x=revenue)) + 
  geom_histogram(bins=30, fill="green") + 
  scale_x_continuous(labels = dollar_format(prefix = "$", suffix = "", big.mark = ",")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + # Нахил тексту
  ggtitle("Дохід") +
  xlab("Дохід (в доларах)")

p3 <- ggplot(TMDB_cleaned, aes(x=runtime)) + 
  geom_histogram(bins=30, fill="red") + 
  theme_minimal() + 
  ggtitle("Тривалість") +
  xlab("Тривалість (у хвилинах)")

# Графік середнього рейтингу
p4 <- ggplot(TMDB_cleaned, aes(x=vote_average)) + 
  geom_histogram(bins=30, fill="orange") + 
  theme_minimal() + 
  ggtitle("Середній Рейтинг")

# Графік року випуску
p5 <- ggplot(TMDB_cleaned, aes(x=release_year)) + 
  geom_histogram(bins=30, fill="purple") + 
  theme_minimal() + 
  ggtitle("Рік Випуску")

# Графік кількості голосів
p6 <- ggplot(TMDB_cleaned, aes(x=vote_count)) + 
  geom_histogram(bins=30, fill="yellow") + 
  theme_minimal() + 
  ggtitle("Кількість Голосів")


# Об'єднання графіків за допомогою patchwork
layout <- (p1 + p2) / (p3 + p4) / (p5 + p6)
layout
```

```{r}
ggplot(TMDB_cleaned, aes(x=revenue)) +
  geom_density(fill="blue", color="black", alpha=0.7) +
  theme_minimal() +
  labs(title="Розподіл касових зборів", x="Касові збори", y="Щільність")
```

```{r}
# Розділяємо жанри на різні рядки
data_expanded <- TMDB_cleaned %>%
  separate_rows(genres, sep = "\\|")
```


```{r}
# Перетворення жанрів на бінарні змінні (dummy variables)
data_dummies <- data_expanded %>%
  pivot_wider(names_from = genres, values_from = genres, values_fill = list(genres = "Absent")) %>%
  mutate(across(-c(original_title, runtime, vote_count, vote_average, release_year, budget, revenue), ~ifelse(. == "Absent", 0, 1)))
```

```{r}
# Перевірка перших та останніх рядків DataFrame
data_dummies <- data_dummies %>% rename(TV_Movie = `TV Movie`)
data_dummies <- data_dummies %>% rename(Science_Fiction = `Science Fiction`)
head(data_dummies)
```

```{r}
# Описова статистика
summary(data_dummies)
```
```{r}
#завантаження пакету ggcorrplot

library(ggcorrplot)

# Кореляційний аналіз
data_numbers <- TMDB_cleaned %>% select(-c(original_title, genres))
correlation_matrix <- cor(data_numbers)
```
```{r}
# Візуалізація кореляційної матриці
ggcorrplot(correlation_matrix, lab = TRUE,title ='Correlation Matrix of Movie Variables', lab_size = 3)
```
```{r}
# Кореляційний аналіз
data_num <- data_dummies %>% select(-c(original_title, runtime, vote_count, release_year, budget, Adventure, Thriller, Fantasy, Crime, Western, Family, Comedy, Mystery, Romance, Music,   Foreign, TV_Movie))
correlation_mat <- cor(data_num)

# Візуалізація кореляційної матриці
ggcorrplot(correlation_mat, lab = TRUE,title ='Correlation Matrix of Movie Variables', lab_size = 3)
```
```{r}
# Побудова графіку Бюджет vs Доходи
ggplot(TMDB_cleaned, aes(x = budget, y = revenue)) +
    geom_point(aes(color = vote_average), alpha = 0.6) +  # Додавання кольору залежно від рейтингу
    geom_smooth(method = "lm", se = FALSE, color = "blue") +  # Лінія регресії
    scale_x_continuous(labels = scales::comma) +  # Форматування осі X
    scale_y_continuous(labels = scales::comma) +  # Форматування осі Y
    labs(title = "Бюджет vs Касові збори", x = "Бюджет (у доларах)", y = "Касові збори (у доларах)") +
    theme_minimal() +  # Застосування теми
    theme(legend.position = "bottom")  # Розміщення легенди
```
```{r}
# Побудова графіку Кількість голосів vs Доходи
ggplot(TMDB_cleaned, aes(x = vote_count, y = revenue)) +
    geom_point(alpha = 0.5) + # використання прозорості для кращого візуального представлення
    geom_smooth(method = "lm", se = FALSE, color = "blue") +  # Лінія регресії
    scale_x_continuous(labels = scales::comma) +  # Форматування осі X
    scale_y_continuous(labels = scales::comma) +  # Форматування осі Y
    theme_minimal() +  # Застосування теми
    labs(title = "Кількість голосів vs Касові збори", x = "Кількість голосів", y = "Касові збори")
```
```{r}
# Створення графіка
ggplot(TMDB_cleaned, aes(x = vote_count, y = vote_average)) +
    geom_point(alpha = 0.5) + # використання прозорості для кращого відображення даних
    geom_smooth(method = "lm", se = FALSE, color = "blue") +  # Лінія регресії
    theme_minimal() +
    labs(title = "Кількість Голосів vs Рейтинг",
         x = "Кількість Голосів",
         y = "Рейтинг")
```




```{r}
genres_data <- data_dummies %>% 
  gather(key=genre, value=value, -original_title, -runtime, -vote_count, -vote_average, -release_year, -budget, -revenue, -Foreign, -TV_Movie) %>% 
  filter(value == 1)

genre_rating <- genres_data %>%
  group_by(genre) %>%
  summarise(avg_rating = mean(vote_average))

ggplot(genre_rating, aes(x=genre, y=avg_rating)) + 
  geom_bar(stat="identity", fill="purple") + 
  coord_flip() +
  labs(title="Середній рейтинг за жанром", x="Жанр", y="Середній рейтинг")
```
```{r}
genres_data <- data_dummies %>% 
  gather(key=genre, value=value, -original_title, -runtime, -vote_count, -vote_average, -release_year, -budget, -revenue, -Foreign, -TV_Movie) %>% 
  filter(value == 1)

genre_rating <- genres_data %>%
  group_by(genre) %>%
  summarise(avg_revenue = mean(revenue))

ggplot(genre_rating, aes(x=genre, y=avg_revenue)) + 
  geom_bar(stat="identity", fill="purple") + 
  coord_flip() +
  labs(title="Середній дохід за жанром", x="Жанр", y="Середній дохід")
```

```{r}
# Підготовка даних: зміна структури даних з широкої на довгу
long_data <- data_dummies %>%
  pivot_longer(
    cols = c(Action, Animation, Science_Fiction, Adventure, Comedy, Documentary, Drama, Thriller, Fantasy, History, Horror, Crime, Western, War, Family, Mystery, Romance, Music), # Замініть на назви ваших жанрових колонок
    names_to = "Genre",
    values_to = "Genre_Present"
  ) %>%
  filter(Genre_Present == 1)

# Розрахунок середнього чистого доходу за жанрами
average_net_revenue_by_genre <- long_data %>%
  group_by(Genre) %>%
  summarize(
    Average_Net_Revenue = mean(revenue - budget, na.rm = TRUE)
  )

# Візуалізація
ggplot(average_net_revenue_by_genre, aes(x = Genre, y = Average_Net_Revenue)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  theme_minimal() +
  coord_flip() + # Для горизонтального бар-графіка
  labs(title = "Середній чистий дохід фільмів за жанрами",
       x = "Жанр",
       y = "Середній чистий дохід (у доларах)")
```
```{r}
genre_count <- genres_data %>%
  group_by(genre) %>%
  count()

ggplot(genre_count, aes(x=genre, y=n)) + 
  geom_bar(stat="identity", fill="cyan") + 
  coord_flip() +
  labs(title="Кількість фільмів за жанром", x="Жанр", y="Кількість фільмів")
```
```{r}
# Групування даних по року випуску та обчислення середніх значень касових зборів і середнього рейтингу
trends <- aggregate(data_dummies[c('revenue', 'vote_average')], by=list(data_dummies$release_year), FUN=mean)
colnames(trends) <- c('release_year', 'avg_revenue', 'avg_vote_average')

# Побудова графіку для касових зборів
g1 <- ggplot(trends, aes(x=release_year, y=avg_revenue)) +
  geom_line() +
  labs(title="Average Revenue Over Years", x="Release Year", y="Average Revenue")

# Побудова графіку для середнього рейтингу
g2 <- ggplot(trends, aes(x=release_year, y=avg_vote_average)) +
  geom_line() +
  labs(title="Average Vote Average Over Years", x="Release Year", y="Average Vote Average")

# Об'єднання графіків за допомогою patchwork
layout <- (g1 / g2)
layout
```
```{r}
# Функція для виявлення викидів за допомогою міжквартильного розмаху (IQR)
detect_outliers <- function(df, feature) {
  Q1 <- quantile(df[[feature]], 0.25)
  Q3 <- quantile(df[[feature]], 0.75)
  IQR <- Q3 - Q1
  lower_bound <- Q1 - 1.5 * IQR
  upper_bound <- Q3 + 1.5 * IQR
  
  return(which(df[[feature]] < lower_bound | df[[feature]] > upper_bound))
}

# Виявлення викидів для бюджету, касових зборів, тривалості та кількості голосів
outliers_budget <- detect_outliers(data_dummies, 'budget')
outliers_revenue <- detect_outliers(data_dummies, 'revenue')
outliers_runtime <- detect_outliers(data_dummies, 'runtime')
outliers_vote_count <- detect_outliers(data_dummies, 'vote_count')

# Об'єднання всіх індексів викидів
all_outliers <- c(outliers_budget, outliers_revenue, outliers_runtime, outliers_vote_count)

# Видалення викидів з датасету
movies_data_clean <- data_dummies[-unique(all_outliers), ]

# Перегляд оновлених статистик
summary(movies_data_clean)
```

```{r}
# Вибір змінних для моделі
predictors <- c("budget", "runtime", "vote_count", "release_year")

# Підготовка даних для моделі касових зборів
X_revenue <- data_dummies %>% select(all_of(predictors))
y_revenue <- data_dummies$revenue

# Розбиття даних на тренувальні та тестові набори
set.seed(42)
train_index <- sample(1:nrow(X_revenue), 0.7 * nrow(X_revenue))
X_train_rev <- X_revenue[train_index, ]
y_train_rev <- y_revenue[train_index]
X_test_rev <- X_revenue[-train_index, ]
y_test_rev <- y_revenue[-train_index]

# Побудова моделі лінійної регресії
model_revenue <- lm(y_train_rev ~ ., data = X_train_rev)
summary(model_revenue)

# Прогнозування та оцінка моделі
predictions_rev <- predict(model_revenue, X_test_rev)
MSE_revenue <- mean((predictions_rev - y_test_rev)^2)
R2_revenue <- summary(model_revenue)$r.squared

# Виведення результатів
cat("MSE for Revenue Model: ", MSE_revenue, "\n")
cat("R2 for Revenue Model: ", R2_revenue, "\n")

```


```{r}
# Вибір змінних для моделі
predictors <- c("budget", "runtime", "vote_count", "release_year")
# Підготовка даних для моделі середнього рейтингу голосування
X_vote <- data_dummies %>% select(all_of(predictors))
y_vote <- data_dummies$vote_average

# Розбиття даних на тренувальні та тестові набори
set.seed(42)
train_index_vote <- sample(1:nrow(X_vote), 0.7 * nrow(X_vote))
X_train_vote <- X_vote[train_index_vote, ]
y_train_vote <- y_vote[train_index_vote]
X_test_vote <- X_vote[-train_index_vote, ]
y_test_vote <- y_vote[-train_index_vote]

# Побудова моделі лінійної регресії
model_vote <- lm(y_train_vote ~ ., data = X_train_vote)
summary(model_vote)

# Прогнозування та оцінка моделі
predictions_vote <- predict(model_vote, X_test_vote)
MSE_vote <- mean((predictions_vote - y_test_vote)^2)
R2_vote <- summary(model_vote)$r.squared

# Виведення результатів
cat("MSE for Vote Average Model: ", MSE_vote, "\n")
cat("R2 for Vote Average Model: ", R2_vote, "\n")

```
```{r}
library(randomForest)

# Підготовка даних для аналізу касових зборів
# Видаляємо непотрібні стовпці
movies_for_revenue <- data_dummies[, !(names(data_dummies) %in% c('Unnamed: 0', 'original_title', 'revenue', 'TV_Movie', 'Foreign'))]

# Визначаємо змінну для прогнозування
revenue <- data_dummies$revenue

# Розділяємо дані на навчальний та тестовий набори (70% на 30%)
set.seed(42) # для відтворюваності результатів
train_indices <- sample(1:nrow(movies_for_revenue), 0.7*nrow(movies_for_revenue))
train_data_revenue <- movies_for_revenue[train_indices, ]
train_revenue <- revenue[train_indices]

test_data_revenue <- movies_for_revenue[-train_indices, ]
test_revenue <- revenue[-train_indices]

# Створення моделі випадкового лісу для касових зборів
rf_revenue <- randomForest(x = train_data_revenue, y = train_revenue, ntree = 100, importance = TRUE)

# Оцінка моделі
revenue_pred <- predict(rf_revenue, test_data_revenue)
revenue_rsquare <- cor(test_revenue, revenue_pred)^2

# Виведення результату
print(paste('R-squared for revenue model:', revenue_rsquare))


# Перетворюємо дані важливості змінних у data frame
importance_revenue <- importance(rf_revenue, type = 1) # type 1 для %IncMSE
importance_revenue_df <- data.frame(Feature = rownames(importance_revenue), 
                                    Importance = importance_revenue[, 1])

# Відсортуємо змінні за зменшенням важливості
importance_revenue_df <- importance_revenue_df[order(importance_revenue_df$Importance, decreasing = TRUE), ]

# Створимо графік важливості змінних для касових зборів
ggplot(importance_revenue_df, aes(x = reorder(Feature, Importance), y = Importance)) +
  geom_bar(stat = 'identity') +
  coord_flip() + # Перевертаємо графік для кращого відображення
  xlab('') + 
  ylab('% Increase in MSE') + 
  ggtitle('Feature Importance for Revenue Model') +
  theme_minimal()
```
```{r}
# Аналогічно для аналізу рейтингу фільму
movies_for_rating <- data_dummies[, !(names(data_dummies) %in% c('Unnamed: 0', 'original_title', 'vote_average', 'TV_Movie', 'Foreign'))]
rating <- data_dummies$vote_average

# Розділяємо дані
set.seed(42) # для відтворюваності результатів
train_data_rating <- movies_for_rating[train_indices, ]
train_rating <- rating[train_indices]

test_data_rating <- movies_for_rating[-train_indices, ]
test_rating <- rating[-train_indices]

# Створення моделі випадкового лісу для рейтингу
rf_rating <- randomForest(x = train_data_rating, y = train_rating, ntree = 100, importance = TRUE)

# Оцінка моделі
rating_pred <- predict(rf_rating, test_data_rating)
rating_rsquare <- cor(test_rating, rating_pred)^2

# Виведення результату
print(paste('R-squared for rating model:', rating_rsquare))

# Важливість змінних
importance_rating <- importance(rf_rating)

# Перетворюємо дані важливості змінних у data frame
importance_rating_df <- data.frame(Feature=rownames(importance_rating), 
                                    Importance=importance_rating[,'%IncMSE'])

# Відсортуємо змінні за зменшенням важливості
importance_rating_df <- importance_rating_df[order(-importance_rating_df$Importance), ]

# Створимо графік важливості змінних для рейтингу
ggplot(importance_rating_df, aes(x=reorder(Feature, Importance), y=Importance)) +
  geom_bar(stat='identity') +
  coord_flip() + # Перевертаємо графік для кращого відображення
  xlab('') + 
  ylab('% Increase in MSE') + 
  ggtitle('Feature Importance for Rating Model') +
  theme_minimal()
```
